import os

class ENV:
    def setup(self):
        os.system("pip install JPype1==0.7.0")
        os.system("pip install Keras-Applications==1.0.8")
        os.system("pip install Keras-Preprocessing==1.1.2")
        os.system("pip install Markdown==3.3.3")
        os.system("pip install Werkzeug==1.0.1")
        os.system("pip install absl-py==0.11.0")
        os.system("pip install astor==0.8.1")
        os.system("pip install cached-property==1.5.2")
        os.system("pip install gast==0.2.2")
        os.system("pip install google-pasta==0.2.0")
        os.system("pip install grpcio==1.34.1")
        os.system("pip install h5py==3.1.0")
        os.system("pip install importlib-metadata==3.4.0")
        os.system("pip install jieba==0.42.1")
        os.system("pip install joblib==1.0.0")
        os.system("pip install numpy==1.19.5")
        os.system("pip install opt-einsum==3.3.0")
        os.system("pip install pandas==1.2.0")
        os.system("pip install pip==10.0.1")
        os.system("pip install protobuf==3.14.0")
        os.system("pip install pyhanlp==0.1.66")
        os.system("pip install python-dateutil==2.8.1")
        os.system("pip install pytz==2020.5")
        os.system("pip install scikit-learn==0.24.0")
        os.system("pip install scipy==1.6.0")
        os.system("pip install setuptools==51.1.2")
        os.system("pip install six==1.15.0")
        os.system("pip install sklearn==0.0")
        os.system("pip install tensorboard==1.15.0")
        os.system("pip install tensorflow==1.15.0")
        os.system("pip install tensorflow-estimator==1.15.1")
        os.system("pip install termcolor==1.1.0")
        os.system("pip install threadpoolctl==2.1.0")
        os.system("pip install typing-extensions==3.7.4.3")
        os.system("pip install wheel==0.36.2")
        os.system("pip install wrapt==1.12.1")
        os.system("pip install zipp==3.4.0")